### ISSUE TITLE
大佬你好，我想看看你这个项目的数据库文件可以吗

### ISSUE THREAD

**Issue by hjx424** [zach-xing/Simple-chat#1]
大佬你好，我想看看你这个项目的数据库文件可以吗

**Comment by zach-xing** [comment]
（不是大佬😄，这个是当时用作学习写的一个简单聊天）
抱歉，这项目太过久远了，数据库的文件已经丢失了。🤣
不过这个项目有关数据库其实只有一个登录/注册的操作，也就是只有一个 User 表。里面好像只有 name、password 这些信息而已。
具体的一些数据库的操作看这里：
https://github.com/Zeekg-zk/Simple-chat/blob/master/src/Client/JDBCUtils.java

**Comment by hjx424** [comment]
好的谢谢啦
